apiVersion: v1
kind: Service
metadata:
  name: {{ include "oberth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oberth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oberth.selectorLabels" . | nindent 4 }}
  ports:
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: ssh
      nodePort: {{ .Values.service.sshNodePort }}
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      nodePort: {{ .Values.service.httpsNodePort }}
      protocol: TCP
